# Generated by Django 5.1.7 on 2025-03-28 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="start_time",
        ),
    ]
