# Generated by Django 4.2.13 on 2025-04-11 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0003_topic_end_time_topic_is_timer_running_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="is_timer_running",
        ),
    ]
